//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class member
    {
        public int id { get; set; }

        [Required(ErrorMessage = "name必需填寫，不可空白")]
        [RegularExpression(@"^[\u4e00-\u9fa5a-zA-Z]{2,}$", ErrorMessage = "至少2中英文字元")]
        public string name { get; set; }

        [Required(ErrorMessage = "username必需填寫，不可空白")]
        [RegularExpression(@"^\w{4,}$", ErrorMessage = "至少4個英文字元，可加底線")]
        public string username { get; set; }

        [Required(ErrorMessage ="password必需填寫，不可空白")]
        [RegularExpression(@"^\w{6,}$", ErrorMessage = "至少6個英文字元，可加底線")]
        public string password { get; set; }

        [Required(ErrorMessage = "registerDate必需填寫，不可空白")]
        public Nullable<System.DateTime> registerDate { get; set; }
    }
}
